services:
  - type: web
    name: client
    env: node
    buildCommand: "cd client && npm install && npm run build"
    startCommand: "cd client && npm start"

  - type: web
    name: server
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && node server.js"
